name: Run Tests
# Trigger this workflow on every push or pull request
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-selenium

      - name: Where am I?
        run: |
          pwd
          ls -R
    
      - name: Test with PyTest
        run: pytest tests --html=tests/Reports/Report.html  
 
      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: PytestReport           # Name of the folder
          path: tests/Reports          # Path to test results
